"""empty message

Revision ID: 511ba32d5b33
Revises: b43dedc54e25
Create Date: 2024-08-01 11:11:08.389922

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '511ba32d5b33'
down_revision = 'b43dedc54e25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=100), nullable=False),
    sa.Column('domain', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('address'),
    sa.UniqueConstraint('domain')
    )
    with op.batch_alter_table('chat_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.drop_column('create_at')
        batch_op.drop_column('update_at')

    with op.batch_alter_table('score', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.drop_column('create_at')
        batch_op.drop_column('update_at')

    with op.batch_alter_table('score_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.drop_column('create_at')
        batch_op.drop_column('update_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('score_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('update_at', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('create_at', sa.DATETIME(), nullable=True))
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('score', schema=None) as batch_op:
        batch_op.add_column(sa.Column('update_at', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('create_at', sa.DATETIME(), nullable=True))
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('chat_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('update_at', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('create_at', sa.DATETIME(), nullable=True))
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    op.drop_table('user')
    # ### end Alembic commands ###
